# Configuración para Vault
vault:
  enabled: true
  address: "http://vault-address:8200"  # Dirección de Vault
  tokenSecretName: "vault-token-secret"  # Nombre del Secret con el token
  tokenSecretKey: "token"  # Clave del Secret que contiene el token
  secretPath: "secret/myapp"  # Ruta del secreto en Vault

# Configuración para el Job que obtiene secretos de Vault
job:
  enabled: true
  name: "vault-to-k8s-secret"  # Nombre del Job
  image: "hashicorp/vault:latest"  # Imagen de Vault
  command: ["sh", "-c", "vault kv get -format=json {{ .Values.vault.secretPath }} | jq -r '.data.data' > /mnt/secrets/myapp.json"]
  restartPolicy: OnFailure
  volumeMounts:
    - name: secret-volume
      mountPath: /mnt/secrets
  volumes:
    - name: secret-volume
      emptyDir: {}

# Configuración para el Deployment de la app
app:
  replicaCount: 2
  image:
    repository: myrepo/myapp  # Repositorio de la imagen de la app
    tag: "latest"  # Etiqueta de la imagen
    pullPolicy: IfNotPresent  # Política de obtención de la imagen
  service:
    type: ClusterIP
    port: 80

# Resource limits and requests for the app container
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

# Liveness and readiness probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    path: /health
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    path: /ready

# Horizontal Pod Autoscaler (HPA)
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# PersistentVolumeClaim (PVC) configuration
pvc:
  enabled: true
  name: "myapp-pvc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"  # Tamaño del almacenamiento solicitado

# Ingress configuration
ingress:
  enabled: true
  hostname: myapp.example.com
  annotations: {}

# Kubernetes Secrets configuration for storing app-related secrets
k8sSecret:
  name: "myapp-secret"  # Nombre del secreto en Kubernetes
  data:
    mysecretkey: "<base64_encoded_value>"  # Placeholder para el valor codificado en base64
