{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage }}
{{- end }}
