apiVersion: v1  
kind: Secret  
metadata:  
  name: myapp-secret  
type: Opaque  
data:  
  # Aquí puedes cargar los secretos que hayas obtenido de Vault  
  mysecretkey: <base64_encoded_value>  # Inserta el valor codificado en base64  
