apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.tokenSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.vault.token | b64enc | quote }}

  mysecretkey: <base64_encoded_value>  # Inserta el valor codificado en base64  
