apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-myapp-service
spec:
  selector:
    app: {{ .Release.Name }}-myapp
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}

